---
title: "Analysis"
output: html_notebook
---

```{r}
library(tidyverse)
library(GGally)
```

```{r}
lending_loans <- read_csv(here("clean_data/lending_loans.csv"))
```

```{r}
# check for aliases in the independent variables
alias(default_loan ~ ., data = lending_loans)
```

```{r}
# convert variables with 0 and 1 to logical
lending_loans <- lending_loans %>% 
  mutate(delinq_2yrs = as.logical(delinq_2yrs),
         inq_last_6mths = as.logical(inq_last_6mths),
         pub_rec = as.logical(pub_rec),
         out_prncp = as.logical(out_prncp),
         total_rec_late_fee = as.logical(total_rec_late_fee),
         recoveries = as.logical(recoveries),
         collection_recovery_fee = as.logical(collection_recovery_fee),
         default_loan = as.logical(default_loan))

loans_numeric <- lending_loans %>%
  select_if(is.numeric)

loans_nonnumeric <- lending_loans %>%
  select_if(function(x) !is.numeric(x)) %>% 
  select(-addr_state)

loans_numeric$default_loan <- lending_loans$default_loan

ggpairs(loans_numeric)
```

```{r}
ggpairs(loans_nonnumeric)
```

